# Generated by Django 3.1.2 on 2020-11-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopyText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FrequentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=150)),
                ('answer_text', models.TextField()),
                ('votes', models.IntegerField()),
            ],
        ),
    ]
