# Generated by Django 3.1.2 on 2020-11-07 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentQuestion',
            fields=[
                ('copytext_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sitecore.copytext')),
                ('question_text', models.CharField(max_length=150)),
                ('votes', models.IntegerField()),
            ],
            bases=('sitecore.copytext',),
        ),
    ]
