# Generated by Django 3.1.2 on 2020-11-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copytext',
            name='title',
            field=models.CharField(default='test title', max_length=50),
            preserve_default=False,
        ),
    ]
