# Generated by Django 3.1.2 on 2021-02-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0003_auto_20210201_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='copytext',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
