# Generated by Django 3.1.2 on 2021-03-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0004_copytext_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='copytext',
            name='title',
        ),
    ]
