# Generated by Django 3.1.2 on 2021-03-03 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0005_auto_20210302_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copytext',
            name='page',
        ),
        migrations.AddField(
            model_name='copytext',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitecore.sectiontitle'),
        ),
        migrations.AddField(
            model_name='sectiontitle',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitecore.page'),
        ),
    ]
