# Generated by Django 3.1.2 on 2021-03-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0006_auto_20210302_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copytext',
            name='label',
        ),
        migrations.AlterField(
            model_name='page',
            name='label',
            field=models.CharField(default='djangodbmodelsfieldscharfield', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sectiontitle',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
