# Generated by Django 3.1.2 on 2021-03-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecore', '0007_auto_20210311_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='label',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
