# Generated by Django 3.1.6 on 2021-08-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_learningresource_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='learningresource',
            name='tagline',
            field=models.CharField(default='Enter a tag line', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='learningresource',
            name='tags',
            field=models.ManyToManyField(to='resources.CategoryTag'),
        ),
    ]
