# Generated by Django 3.1.6 on 2021-08-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20210807_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningresource',
            name='tags',
            field=models.ManyToManyField(null=True, to='resources.CategoryTag'),
        ),
    ]
