# Generated by Django 3.1.6 on 2021-08-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20210807_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='description',
            field=models.TextField(default='Enter a resource descripiton', null=True),
        ),
    ]
