# Generated by Django 3.1.2 on 2021-03-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerproject',
            name='project_description',
        ),
        migrations.AddField(
            model_name='volunteerproject',
            name='title',
            field=models.CharField(default='test title', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerprojectdetail',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerprojectdetailcategory',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
