# Generated by Django 3.1.6 on 2021-08-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0003_auto_20210804_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerproject',
            name='tags',
            field=models.ManyToManyField(null=True, to='volunteering.CategoryTag'),
        ),
    ]
