# Generated by Django 3.1.6 on 2021-08-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0004_auto_20210807_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerproject',
            name='tags',
            field=models.ManyToManyField(to='volunteering.CategoryTag'),
        ),
    ]
